target("lcui-css")
    set_kind("static")
    add_files("src/*.c")
    add_deps("yutil")

target("lcui-css-test")
    set_default(false)
    set_kind("binary")
    add_files("test/*.c")
    add_deps("ctest", "yutil", "lcui-css")
